const tintColorLight = "#0a7ea4";
const tintColorBlue = "#007AFF";

export const Colors = {
  light: {
    text: "#FFFFFF",
    secondaryText: "#000000",
    background: "#FEFEFE",
    secondaryBackground: "#292D3C",
    highlight: "#FED32C",
    secondaryHighlight: "#DA7806",
    icon: "#687076",
    success: "#66FFA7",
    warning: "#FF6B6B",
    tabIconDefault: "#687076",
    tabIconSelected: tintColorLight,
  },
  dark: {
    text: "#000000",
    secondaryText: "#FFFFFF",
    background: "#202128",
    secondaryBackground: "#292D3C",
    highlight: "#FED32C",
    secondaryHighlight: "#DA7806",
    icon: "#00AAFF",
    success: "#66FFA7",
    warning: "#FF6B6B",
    tabIconDefault: "#9BA1A6",
    tabIconSelected: "#00AAFF",
  },
  blue: {
    text: "#ffffff",
    secondaryText: "#FFFFFF",
    background: "#0055D4",
    secondaryBackground: "#BCEB0B",
    highlight: "#FED32C",
    secondaryHighlight: "#DA7806",
    tint: tintColorBlue,
    icon: "#E1E8FF",
    success: "#66FFA7",
    warning: "#FF6B6B",
    tabIconDefault: "#E1E8FF",
    tabIconSelected: tintColorBlue,
  },
};
